package com.example.streetbellpos.options;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;


@IntDef({GLIDE_TRANSFORM_OPTION.NO_TRANSFORM, GLIDE_TRANSFORM_OPTION.CIRCLE_TRANSFORM_NO_BORDER, GLIDE_TRANSFORM_OPTION.CIRCLE_TRANSFORM_WHITE_BORDER, GLIDE_TRANSFORM_OPTION.SQUARE_CROP_TRANFRORM, GLIDE_TRANSFORM_OPTION.ROUNDER_CORNER_TRANSFORM, GLIDE_TRANSFORM_OPTION.CIRCLE_TRANSFORM_BLACK_BORDER, GLIDE_TRANSFORM_OPTION.SQUARE_ROUNDED_CORNER_TRANSFORM})
@Retention(RetentionPolicy.SOURCE)
public @interface GLIDE_TRANSFORM_OPTION {
    int NO_TRANSFORM = 0;
    int CIRCLE_TRANSFORM_NO_BORDER = 1;
    int CIRCLE_TRANSFORM_WHITE_BORDER = 2;
    int SQUARE_CROP_TRANFRORM = 3;
    int ROUNDER_CORNER_TRANSFORM = 4;
    int CIRCLE_TRANSFORM_BLACK_BORDER = 5;
    int SQUARE_ROUNDED_CORNER_TRANSFORM = 6;
}
